#ifndef U8CHAR_H
#define U8CHAR_H
#include <wchar.h>

char* u8trim(char* str);
int u8strlenc(char* str);
int u8strlencc(const char* str);
int u8charleni(int n);
int u8charlenc(char* c);
int u8charlencc(const char* c);
char* u8shiftc(char* str, int len);
const char* u8shiftcc(const char* str, int len);
const char* u8charc(char* str);
const char* u8charcc(const char* str);
int u8tointc(char* str);
int u8tointcc(const char* str);
const char* inttou8(int n);
int u8stowcs(wchar_t* to, const char* from);
int wcstou8s(char* to, const wchar_t* from);
int inttou8s(int n, char* target);
int u8toupper(int chr);
int u8tolower(int chr);

#ifdef __cplusplus
  int u8charlen(int n);
  int u8charlen(char* c);
  int u8charlen(const char* c);
  int u8strlen(char* c);
  int u8strlen(const char* c);
  char* u8shift(char*& str, int len=1);
  const char* u8shift(const char*& str, int len=1);
  const char* u8char(char* str);
  const char* u8char(const char* str);
  int u8toint(char* str);
  int u8toint(const char* str);
#endif

int u8isdigiti(int n);
int u8isdigitc(char* c);
int u8isdigitcc(const char* c);
int u8isupperasciii(int n);
int u8isupperasciic(char* c);
int u8isupperasciicc(const char* c);
int u8islowerasciii(int n);
int u8islowerasciic(char* c);
int u8islowerasciicc(const char* c);
int u8isasciiletteri(int n);
int u8isasciiletterc(char* c);
int u8isasciilettercc(const char* c);
int u8isuppergreeki(int n);
int u8isuppergreekc(char* c);
int u8isuppergreekcc(const char* c);
int u8islowergreeki(int n);
int u8islowergreekc(char* c);
int u8islowergreekcc(const char* c);
int u8isgreeki(int n);
int u8isgreekc(char* c);
int u8isgreekcc(const char* c);
int u8isbasespacei(int n);
int u8isbasespacec(char* c);
int u8isbasespacecc(const char* c);
int u8isspacei(int n);
int u8isspacec(char* c);
int u8isspacecc(const char* c);
int u8islowerlatini(int n);
int u8islowerlatinc(char* c);
int u8islowerlatincc(const char* c);
int u8isupperlatini(int n);
int u8isupperlatinc(char* c);
int u8isupperlatincc(const char* c);
int u8islatini(int n);
int u8islatinc(char* c);
int u8islatincc(const char* c);
int u8isbasesigni(int n);
int u8isbasesignc(char* c);
int u8isbasesigncc(const char* c);
int u8islatinsigni(int n);
int u8islatinsignc(char* c);
int u8islatinsigncc(const char* c);
int u8issigni(int n);
int u8issignc(char* c);
int u8issigncc(const char* c);
int u8isuppercyrilici(int n);
int u8isuppercyrilicc(char* c);
int u8isuppercyriliccc(const char* c);
int u8islowercyrilici(int n);
int u8islowercyrilicc(char* c);
int u8islowercyriliccc(const char* c);
int u8iscyrilici(int n);
int u8iscyrilicc(char* c);
int u8iscyriliccc(const char* c);
int u8isloweri(int n);
int u8islowerc(char* c);
int u8islowercc(const char* c);
int u8isupperi(int n);
int u8isupperc(char* c);
int u8isuppercc(const char* c);

#ifdef __cplusplus
int u8isdigit(int n);
int u8isdigit(char* c);
int u8isdigit(const char* c);
int u8isupperascii(int n);
int u8isupperascii(char* c);
int u8isupperascii(const char* c);
int u8islowerascii(int n);
int u8islowerascii(char* c);
int u8islowerascii(const char* c);
int u8isasciiletter(int n);
int u8isasciiletter(char* c);
int u8isasciiletter(const char* c);
int u8isuppergreek(int n);
int u8isuppergreek(char* c);
int u8isuppergreek(const char* c);
int u8islowergreek(int n);
int u8islowergreek(char* c);
int u8islowergreek(const char* c);
int u8isgreek(int n);
int u8isgreek(char* c);
int u8isgreek(const char* c);
int u8isbasespace(int n);
int u8isbasespace(char* c);
int u8isbasespace(const char* c);
int u8isspace(int n);
int u8isspace(char* c);
int u8isspace(const char* c);
int u8islowerlatin(int n);
int u8islowerlatin(char* c);
int u8islowerlatin(const char* c);
int u8isupperlatin(int n);
int u8isupperlatin(char* c);
int u8isupperlatin(const char* c);
int u8islatin(int n);
int u8islatin(char* c);
int u8islatin(const char* c);
int u8isbasesign(int n);
int u8isbasesign(char* c);
int u8isbasesign(const char* c);
int u8islatinsign(int n);
int u8islatinsign(char* c);
int u8islatinsign(const char* c);
int u8issign(int n);
int u8issign(char* c);
int u8issign(const char* c);
int u8isuppercyrilic(int n);
int u8isuppercyrilic(char* c);
int u8isuppercyrilic(const char* c);
int u8islowercyrilic(int n);
int u8islowercyrilic(char* c);
int u8islowercyrilic(const char* c);
int u8iscyrilic(int n);
int u8iscyrilic(char* c);
int u8iscyrilic(const char* c);
int u8islower(int n);
int u8islower(char* c);
int u8islower(const char* c);
int u8isupper(int n);
int u8isupper(char* c);
int u8isupper(const char* c);
#endif

extern int u8scanf_chars;
extern int u8scanf_bytes;
int u8scanf(const char* input, const char* format, ...);

#endif